<div class="row mt-5">
  <div class="col-md-6">
    <div class="card card-body bg-dark text-white">
      <h1>Cadastro de Chamado</h1>
      <hr>
      <p>Lorem Ipsum...</p>
    </div>
  </div>

  <div class="col-md-6">
      <div class="card">
          <div class="card-body">
              <form action="" method="post">
                  <label for="type">Tipo: </label>
                  <select class="form-control" name="type" id="type" required>
                    <option value=""> -- Selecione -- </option>
                  </select>
                  <br>

                  <label for="title">Titulo: </label>
                  <input
                    type="text" name="title" placeholder="O que aconteceu?"
                    id="title" class="form-control" required>
                  <br>

                  <label for="description">Descrição: </label>
                  <textarea
                    name="description" placeholder="Descrição do Problema"
                    id="description" class="form-control" required></textarea>
                  <br>

                  <button class="btn btn-primary btn-block">CONFIRMAR</button>
              </form>
          </div>
      </div>
  </div>
</div>
