<div class="row mt-5">
  <div class="col-md-12">
    <div class="card card-body">
      <table class="table table-hover table-striped">
        <thead class="thead-dark">
            <tr>
                <th>Titulo</th>
                <th>Tipo</th>
                <th>Status</th>
                <th>Autor</th>
                <th>Data</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
          <tr>
            <td>Titulo do Ticket</td>
            <td>Tipo</td>
            <td>Status</td>
            <td>Autor</td>
            <td>Data</td>
            <td>
              <a href="#" class="btn btn-sm btn-warning">Editar</a>
              <a href="#" class="btn btn-sm btn-danger">Excluir</a>
            </td>
          </tr>
          <tr>
            <td>Titulo do Ticket</td>
            <td>Tipo</td>
            <td>Status</td>
            <td>Autor</td>
            <td>Data</td>
            <td>
              <a href="#" class="btn btn-sm btn-warning">Editar</a>
              <a href="#" class="btn btn-sm btn-danger">Excluir</a>
            </td>
          </tr>
          <tr>
            <td>Titulo do Ticket</td>
            <td>Tipo</td>
            <td>Status</td>
            <td>Autor</td>
            <td>Data</td>
            <td>
              <a href="#" class="btn btn-sm btn-warning">Editar</a>
              <a href="#" class="btn btn-sm btn-danger">Excluir</a>
            </td>
          </tr>
          <tr>
            <td>Titulo do Ticket</td>
            <td>Tipo</td>
            <td>Status</td>
            <td>Autor</td>
            <td>Data</td>
            <td>
              <a href="#" class="btn btn-sm btn-warning">Editar</a>
              <a href="#" class="btn btn-sm btn-danger">Excluir</a>
            </td>
          </tr>
          <tr>
            <td>Titulo do Ticket</td>
            <td>Tipo</td>
            <td>Status</td>
            <td>Autor</td>
            <td>Data</td>
            <td>
              <a href="#" class="btn btn-sm btn-warning">Editar</a>
              <a href="#" class="btn btn-sm btn-danger">Excluir</a>
            </td>
          </tr>
          <tr>
            <td>Titulo do Ticket</td>
            <td>Tipo</td>
            <td>Status</td>
            <td>Autor</td>
            <td>Data</td>
            <td>
              <a href="#" class="btn btn-sm btn-warning">Editar</a>
              <a href="#" class="btn btn-sm btn-danger">Excluir</a>
            </td>
          </tr>

        </tbody>
      </table>
    </div>
  </div>
</div>
