<div class="row mt-5">
  <div class="col-md-3">
    <div class="card text-white bg-danger">
      <div class="card-body">
        <h5 class="card-title h3">99 Abertos</h5>
      </div>
    </div>
  </div>

  <div class="col-md-3">
    <div class="card text-white bg-success">
      <div class="card-body">
        <h5 class="card-title h3">99 Resolvidos</h5>
      </div>
    </div>
  </div>

  <div class="col-md-3">
    <div class="card text-white bg-warning">
      <div class="card-body">
        <h5 class="card-title h3">99 Andamento</h5>
      </div>
    </div>
  </div>

  <div class="col-md-3">
    <div class="card text-white bg-info">
      <div class="card-body">
        <h5 class="card-title h3">99 Cancelados</h5>
      </div>
    </div>
  </div>
</div>
