<div class="row mt-5">
  <div class="col-md-12">
    <div class="card card-body">
      <table class="table table-hover table-striped">
        <thead class="thead-dark">
            <tr>
                <th>Nome</th>
                <th>Descrição</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
          <tr>
            <td>Nome do Departamento</td>
            <td>Descrição...</td>
            <td>
              <a href="#" class="btn btn-sm btn-warning">Editar</a>
              <a href="#" class="btn btn-sm btn-danger">Excluir</a>
            </td>
          </tr>
          <tr>
            <td>Nome do Departamento</td>
            <td>Descrição...</td>
            <td>
              <a href="#" class="btn btn-sm btn-warning">Editar</a>
              <a href="#" class="btn btn-sm btn-danger">Excluir</a>
            </td>
          </tr>
          <tr>
            <td>Nome do Departamento</td>
            <td>Descrição...</td>
            <td>
              <a href="#" class="btn btn-sm btn-warning">Editar</a>
              <a href="#" class="btn btn-sm btn-danger">Excluir</a>
            </td>
          </tr>
          <tr>
            <td>Nome do Departamento</td>
            <td>Descrição...</td>
            <td>
              <a href="#" class="btn btn-sm btn-warning">Editar</a>
              <a href="#" class="btn btn-sm btn-danger">Excluir</a>
            </td>
          </tr>
          <tr>
            <td>Nome do Departamento</td>
            <td>Descrição...</td>
            <td>
              <a href="#" class="btn btn-sm btn-warning">Editar</a>
              <a href="#" class="btn btn-sm btn-danger">Excluir</a>
            </td>
          </tr>
          <tr>
            <td>Nome do Departamento</td>
            <td>Descrição...</td>
            <td>
              <a href="#" class="btn btn-sm btn-warning">Editar</a>
              <a href="#" class="btn btn-sm btn-danger">Excluir</a>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
