<div class="row mt-5">
  <div class="col-md-6">
    <div class="card card-body bg-dark text-white">
      <h1>Cadastro de Usuário</h1>
      <hr>
      <p>Lorem Ipsum...</p>
    </div>
  </div>

  <div class="col-md-6">
      <div class="card">
          <div class="card-body">
              <form action="" method="post">
                  <label for="type">Tipo: </label>
                  <select class="form-control" name="type" id="type">
                    <option value=""> -- Selecione -- </option>
                  </select>
                  <br>

                  <label for="department">Setor/Departamento: </label>
                  <select class="form-control" name="department" id="department">
                    <option value=""> -- Selecione -- </option>
                      <?php
                        foreach ($this->data['departments'] as $department) {
                            echo "<option>{$department->getName()}</option>";
                        }
                      ?>
                  </select>
                  <br>

                  <label for="name">Nome: </label>
                  <input
                    type="text" value="<?=$_POST['name'] ?? ''?>" name="name" placeholder="Nome do Usuário"
                    id="name" class="form-control" required>
                  <br>

                  <label for="email">Email: </label>
                  <input
                    type="text" value="<?=$_POST['email'] ?? ''?>" name="email" placeholder="Email do Usuário"
                    id="email" class="form-control" required>
                  <br>

                  <label for="password">Senha: </label>
                  <input
                    type="password" name="password" placeholder="Senha do Usuário"
                    id="password" class="form-control" required>
                  <br>

                  <button class="btn btn-primary btn-block">CONFIRMAR</button>
              </form>
          </div>
      </div>
  </div>
</div>
