<div class="row mt-5">
  <div class="col-md-12">
    <div class="card card-body">
      <table class="table table-hover table-striped">
        <thead class="thead-dark">
            <tr>
                <th>Nome</th>
                <th>Email</th>
                <th>Departamento</th>
                <th>Tipo</th>
                <th>Criado em</th>
                <th>Atualizado em</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
        <?php
        foreach ($this->data['users'] as $user) {
            echo '<tr>';
                echo "<td>{$user->getName()}</td>";
                echo "<td>{$user->getEmail()}</td>";
                echo "<td>{$user->getDepartment()->getName()}</td>";
                echo "<td>{$user->getType()}</td>";
                echo "<td>{$user->getRegisteredAt()->format('d/m/Y H:i:s')}</td>";
            echo '</tr>';
        }
        ?>
        </tbody>
      </table>
    </div>
  </div>
</div>
