<div class="row mt-5">
  <div class="col-md-12">
    <div class="card card-body">
      <table class="table table-hover table-striped">
        <thead class="thead-dark">
            <tr>
                <th>Nome</th>
                <th>Email</th>
                <th>Departamento</th>
                <th>Tipo</th>
                <th>Criado em</th>
                <th>Atualizado em</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
          <tr>
            <td>Nome do Fulano</td>
            <td>fulano@email.com</td>
            <td>TI</td>
            <td>Suporte</td>
            <td>09/09/2019 12:12:12</td>
            <td>09/09/2019 12:12:12</td>
            <td>
              <a href="#" class="btn btn-sm btn-warning">Editar</a>
              <a href="#" class="btn btn-sm btn-danger">Excluir</a>
            </td>
          </tr>
          <tr>
            <td>Nome do Fulano</td>
            <td>fulano@email.com</td>
            <td>TI</td>
            <td>Suporte</td>
            <td>09/09/2019 12:12:12</td>
            <td>09/09/2019 12:12:12</td>
            <td>
              <a href="#" class="btn btn-sm btn-warning">Editar</a>
              <a href="#" class="btn btn-sm btn-danger">Excluir</a>
            </td>
          </tr>
          <tr>
            <td>Nome do Fulano</td>
            <td>fulano@email.com</td>
            <td>TI</td>
            <td>Suporte</td>
            <td>09/09/2019 12:12:12</td>
            <td>09/09/2019 12:12:12</td>
            <td>
              <a href="#" class="btn btn-sm btn-warning">Editar</a>
              <a href="#" class="btn btn-sm btn-danger">Excluir</a>
            </td>
          </tr>
          <tr>
            <td>Nome do Fulano</td>
            <td>fulano@email.com</td>
            <td>TI</td>
            <td>Suporte</td>
            <td>09/09/2019 12:12:12</td>
            <td>09/09/2019 12:12:12</td>
            <td>
              <a href="#" class="btn btn-sm btn-warning">Editar</a>
              <a href="#" class="btn btn-sm btn-danger">Excluir</a>
            </td>
          </tr>
          <tr>
            <td>Nome do Fulano</td>
            <td>fulano@email.com</td>
            <td>TI</td>
            <td>Suporte</td>
            <td>09/09/2019 12:12:12</td>
            <td>09/09/2019 12:12:12</td>
            <td>
              <a href="#" class="btn btn-sm btn-warning">Editar</a>
              <a href="#" class="btn btn-sm btn-danger">Excluir</a>
            </td>
          </tr>
          <tr>
            <td>Nome do Fulano</td>
            <td>fulano@email.com</td>
            <td>TI</td>
            <td>Suporte</td>
            <td>09/09/2019 12:12:12</td>
            <td>09/09/2019 12:12:12</td>
            <td>
              <a href="#" class="btn btn-sm btn-warning">Editar</a>
              <a href="#" class="btn btn-sm btn-danger">Excluir</a>
            </td>
          </tr>
          <tr>
            <td>Nome do Fulano</td>
            <td>fulano@email.com</td>
            <td>TI</td>
            <td>Suporte</td>
            <td>09/09/2019 12:12:12</td>
            <td>09/09/2019 12:12:12</td>
            <td>
              <a href="#" class="btn btn-sm btn-warning">Editar</a>
              <a href="#" class="btn btn-sm btn-danger">Excluir</a>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
