<div class="row mt-5">
  <div class="col-md-2">
    <div class="card">
      <div class="card-body">FOTO</div>
    </div>
  </div>

  <div class="col-md-6">
    <div class="card">
      <div class="card-body">
        <form>
          <label for="name">Nome: </label>
          <input type="text" name="name" id="name" class="form-control" required>
          <br>

          <label for="email">Email: </label>
          <input type="email" name="email" id="email" class="form-control" required>
          <br>

          <label for="password">Senha: </label>
          <input type="password" name="password" id="password" class="form-control" required>
          <br>

          <button class="btn btn-primary btn-block">ATUALIZAR</button>
        </form>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <div class="card">
      <div class="card-body">
        <strong>Tipo: </strong> Administrador  <br><br>
        <strong>Cadastrado em: </strong> 09/09/2019 10:00:12  <br><br>
        <strong>Atualizado em: </strong> 09/09/2019 10:00:12  <br><br>
        <strong>Último login: </strong> 09/09/2019 10:00:12  <br><br>

      </div>
    </div>
  </div>
</div>
