<section class="row" style="margin-top: 200px">
  <div class="col-md-8 col-xs-12 p-5">
    <h1>HelpDesk - Bla bla bla</h1>
    <h2>A Solução para ajudar a solucionar problemas</h2>
    <hr>
    <p>Lorem Ipsum...</p>

    <button class="btn btn-primary" name="button">Saiba mais</button>
    <button class="btn btn-outline-primary" name="button">Cadastro</button>
  </div>

  <div class="col-md-4 col-xs-12 bg-dark">
    <form class="mt-5 text-white" action="/login" method="post">
      <label for="email" class="mt-3">Email</label>
      <input type="email" id="email" name="email" class="form-control form-control-lg" placeholder="chiquim@email.com" required>
      <br>

      <label for="password">Senha</label>
      <input type="password" id="password" name="password" class="form-control form-control-lg" placeholder="*******" required>
      <br>

      <button class="btn btn-light btn-lg btn-block mb-3">ENTRAR</button>
    </form>
  </div>
</section>
